### ISSUE TITLE
Error when placing entity

### ISSUE THREAD

**Issue by vmadman** [coltonj96/UsefulCombinators#1]
![image](https://cloud.githubusercontent.com/assets/1026490/24331193/a6611fd0-11f4-11e7-952c-9b49d78c616a.png)

When placing an entity, I get the error shown in the screenshot above.

So far I've tried the random and the timer combinators.

I do have a lot of mods loaded but am hoping this is not the result of a conflict, so that I do not need to go through the trouble of unloading mods, etc.  Just let me know.

I am playing in "sandbox" mode, which tends to break a lot of mods, so, maybe that is relevant here.

Thanks,

**Comment by coltonj96** [comment]
What version are you using?
