### ISSUE TITLE
Max combinator breaks when connected to a pole

### ISSUE THREAD

**Issue by loganb** [coltonj96/UsefulCombinators#2]
Hello, 

I'm trying out the aggregate combinators and I noticed an issue when connecting a combinator to a pole. This is on 0.15.3

Steps to reproduce: 
1) Place a max combinator
2) Connect it with a wire to a bare pole
3) Boom! 

![connecting a wire](https://cloud.githubusercontent.com/assets/17287/25764850/a6d4d014-319e-11e7-8ec0-d809ab7f575b.png)

**Comment by coltonj96** [comment]
Fixed now in latest update
